// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlModel

import (
	"time"
)

type CreateUserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Mutation struct {
}

type Profile struct {
	ID          string    `json:"id"`
	DisplayName string    `json:"displayName"`
	Bio         *string   `json:"bio,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
}

type Query struct {
}

type User struct {
	ID        string    `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Profile   *Profile  `json:"profile"`
	CreatedAt time.Time `json:"createdAt"`
}
