root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api/main ./cmd/api/main.go"
bin = "./tmp/api/main"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]

[screen]
clear_on_rebuild = true