version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: g3_server_dev
    ports:
      - "4001:4001"
    volumes:
      - .:/app
    environment:
      - GIN_MODE=debug
    networks:
      - backend


  mongodb:
    image: mongo:latest
    container_name: g3_mongo_dev
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge
