version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    restart: unless-stopped
    networks:
      - backend
    environment:
      - GIN_MODE=release
      - MONGODB_URI=mongodb://mongodb:27017
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:


networks:
  backend:
    driver: bridge
